In [1]:
import pandas as pd
data = pd.read_csv (r' dataScientist.csv')   
df = pd.DataFrame(data, columns= ['company','year_of_experience','description','skills'])
df

,company,year_of_experience,description,skills
0,Analytics Vidhya,2 - 5 yrs,Data ScientistData Scientist RefreshmintGurgao...,"sas , data science , use cases , predict..."
1,Analytics Vidhya,3 - 6 yrs,This Role Is Best Suited ForPerson with 3 yea...,"sas , data science , use cases , predict..."
2,Analytics Vidhya,3 - 5 yrs,"Use SAP , Tableau and Success Factors IT tool...","it tools , tableau , java , vba , data..."
3,Great Learning,0 - 3 yrs,Involve in the residency class room sessions t...,"data analysis , program management , dashb..."
4,Analytics Vidhya,4 - 7 yrs,Data Scientist Delhi NCR ( 4 years of exper...,"information technology , business process ,..."
5,Analytics Vidhya,5 - 8 yrs,The data scientist is responsible for solving ...,"data mining , mobile , business analysis ..."
6,Analytics Vidhya,3 - 6 yrs,The Data Scientist will support our business l...,"visualization , bi , dashboards , data s..."
7,Analytics Vidhya,4 - 7 yrs,Data Scientist- Noida ( 1-3 Years Of Experien...,"data mining , linear regression , sql , ..."
8,Analytics Vidhya,3 - 10 yrs,Requirements: You have expertise in explorator...,"data analysis , data analytics , sas , d..."
9,ITFORTE STAFFING SERVICES PRIVATE LTD,3 - 6 yrs,Data Scientist for GurgaonJob ID IT JOBS#258Lo...,"time series analysis , signal processing , ..."
10,axmiyan hr solutions private limited,3 - 6 yrs,Be an Individual Contributor in the Analytics ...,"time series analysis , linear regression , ..."
11,Crowe LLP,0 - 4 yrs,About Crowe Data ScienceEverything we do is ab...,"docker , git , data structures , python ..."
12,Analytics Vidhya,5 - 8 yrs,Data ScientistData Scientist A Client of Analy...,"algorithms , python , data mining , mach..."
13,Team Computers Pvt Ltd,0 - 3 yrs,Position description: The purpose of this role...,"data visualization , statistical testing ,..."
14,electrifai,10 - 13 yrs,"As a Data Scientist at ElectrifAi , you will ...","hive , algorithms , data mining , sql ,..."
15,Analytics Vidhya,5 - 8 yrs,Data ScientistData Scientist Dollarbird Inform...,"ds , big data , python , oracle , mini..."
16,Sentieo,0 - 3 yrs,Sentieo is powering the future of financial an...,"algorithms , data mining , database , py..."
17,Beno Staffing,2 - 5 yrs,What do we do at BluePi: BluePi is a born in c...,"image processing , algorithms , natural la..."
18,Analytics Vidhya,2 - 7 yrs,Description If you want to forecast Indias eCo...,"algorithms , c , ensemble , ds , sec..."
19,Analytics Vidhya,2 - 5 yrs,Data ScientistData Scientist A Client of Analy...,"hive , algorithms , data mining , sql ,..."
20,Pattem Digital Technologies,0 - 3 yrs,Data Scientist We are searching for a Lead Dat...,"python , data mining , machine learning ,..."
21,MASTERCARD,2 - 3 yrs,Job TitleData ScientistJob Description Integra...,"information technology , ssrs , python , ..."
22,MASTERCARD,2 - 3 yrs,Job TitleData ScientistOverviewIntegrated Anal...,"information technology , ssrs , python , ..."
23,MASTERCARD,2 - 3 yrs,Job TitleData ScientistOverviewIntegrated Anal...,"information technology , ssrs , python , ..."
24,MASTERCARD,0 - 3 yrs,Job TitleData ScientistJob Description Integra...,"information technology , ssrs , python , ..."

In [2]:
import mysql.connector

In [3]:
mydb = mysql.connector.connect(
  host="127.0.0.1",
  user="root",
  passwd="apple123"
)
print(mydb)

<mysql.connector.connection_cext.CMySQLConnection object at 0x7fc39197c710>

In [4]:
mycursor = mydb.cursor()

In [5]:
mycursor.execute('SHOW DATABASES')

In [6]:
for datab in mycursor:
    print(datab)

('information_schema',)
('mydb',)
('mysql',)
('performance_schema',)
('python_db',)
('sys',)

In [7]:
mycursor.execute('USE mydb')

In [8]:
mycursor.execute("CREATE TABLE mydata_table (company VARCHAR(255),year_of_experience VARCHAR(255),description VARCHAR(255),skills VARCHAR(255))")

In [9]:
for i,row in df.iterrows():
            sql = "INSERT INTO mydb.mydata_table VALUES (%s,%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [10]:
# Execute query
sql = "SELECT * FROM mydata_table "
mycursor.execute(sql)

# Fetch all the records
result = mycursor.fetchall()
for i in result:
    print(i)

('Analytics Vidhya', '2 - 5 yrs', 'Data ScientistData Scientist RefreshmintGurgaon INR 4 - 9 LPA Experience : 1 - 3 YRS. Openings: 1Details:Do you feel passionately about solving problems through data? Have you... More Details', 'sas  ,  data science  ,  use cases  ,  predictive modeling  ,  data scientist')
('Analytics Vidhya', '3 - 6 yrs', 'This Role Is Best Suited ForPerson with 3  years of experience in data science. The person should have prior experience with practical data science applications and use cases.... More Details', 'sas  ,  data science  ,  use cases  ,  predictive modeling  ,  data scientist')
('Analytics Vidhya', '3 - 5 yrs', 'Use SAP ,  Tableau and Success Factors IT tools to derive insights from dataApply statistical knowledge to develop data modelsBuild Excel workbooks  ( including VBA ) Prepare ... More Details', 'it tools  ,  tableau  ,  java  ,  vba  ,  data scientist  ,  statistical modeling  ,  visual basic')
('Great Learning', '0 - 3 yrs', 'Involve in the residency class room sessions to facilitate lectures and lab sessionsBe the first point contact for participants for academic queries and manage discussion grou... More Details', 'data analysis  ,  program management  ,  dashboards  ,  tableau  ,  use cases  ,  data scientist')
('Analytics Vidhya', '4 - 7 yrs', 'Data Scientist  Delhi NCR  ( 4  years of experience ) Data Scientist  Delhi NCR  ( 4  years of experience )  A Client of Analytics VidhyaGurugram INR 12 - 17 LPA Experience : ... More Details', 'information technology  ,  business process  ,  data science  ,  predictive modeling  ,  data scientist  ,  statistical modeling')
('Analytics Vidhya', '5 - 8 yrs', 'The data scientist is responsible for solving complex big-data problems in the mobile space using data mining ,  machine learning ,  statistical analysis and common sense. The... More Details', 'data mining  ,  mobile  ,  business analysis  ,  sql  ,  predictive modeling  ,  data scientist  ,  text mining  ,  statistical analysis')
('Analytics Vidhya', '3 - 6 yrs', 'The Data Scientist will support our business leads ,  business analysts and data engineers on data ,  analytics and BI initiatives and will ensure the delivery of actionable a... More Details', 'visualization  ,  bi  ,  dashboards  ,  data science  ,  data scientist  ,  statistical modeling  ,  consulting  ,  predictive analytics  ,  tableau')
('Analytics Vidhya', '4 - 7 yrs', 'Data Scientist- Noida  ( 1-3 Years Of Experience ) Data Scientist- Noida  ( 1-3 Years Of Experience )  A Client of Analytics VidhyaNoida INR 4 - 8 LPA Experience : 1 - 3 YRS. ... More Details', 'data mining  ,  linear regression  ,  sql  ,  data science  ,  data scientist  ,  cluster analysis  ,  logistic regression  ,  sas  ,  consulting  ,  predictive analytics  ,  vba')
('Analytics Vidhya', '3 - 10 yrs', 'Requirements: You have expertise in exploratory data analysis and visualisation  ( e.g. with SQL ,  Python / Pandas ,  R ,  or similar ) .You love using data to answer high-le... More Details', 'data analysis  ,  data analytics  ,  sas  ,  data mining  ,  product roadmap  ,  sql  ,  data science  ,  use cases  ,  predictive modeling  ,  data scientist')
('ITFORTE STAFFING SERVICES PRIVATE LTD', '3 - 6 yrs', 'Data Scientist for GurgaonJob ID IT JOBS#258Location: Gurgaon ,  IndiaRequired Skills: Our client is seeking a creative Data Scientist to explore unstructured data from divers... More Details', 'time series analysis  ,  signal processing  ,  data science  ,  data scientist  ,  statistical modeling  ,  text mining  ,  data analysis  ,  statistical analysis')
('axmiyan hr solutions private limited', '3 - 6 yrs', 'Be an Individual Contributor in the Analytics Research and Development team and solve real-world problems using cutting-edge capabilities and emerging technologies. Be a part ... More Details', 'time series analysis  ,  linear regression  ,  data science  ,  data scientist  ,  logistic regression  ,  image processing  ,  advanced analytics  ,  factor analysis')
('Crowe LLP', '0 - 4 yrs', 'About Crowe Data ScienceEverything we do is about making the future of human work more purposeful. We do this by leveraging state-of-the-art machine learning ,  modern archite... More Details', 'docker  ,  git  ,  data structures  ,  python  ,  machine learning')
('Analytics Vidhya', '5 - 8 yrs', 'Data ScientistData Scientist A Client of Analytics VidhyaGurgaon INR 10 - 15 LPA Experience : 2 - 4 YRS. Openings: 3Details:About the companyStarted 5 years ago ,  today it is... More Details', 'algorithms  ,  python  ,  data mining  ,  machine learning  ,  mysql')
('Team Computers Pvt Ltd', '0 - 3 yrs', 'Position description: The purpose of this role is to closely work with business to identify and implement predictive models for healthcare.Primary Responsibilities:Model for r... More Details', 'data visualization  ,   statistical testing  ,   regression  ,   machine learning techniques')
('electrifai', '10 - 13 yrs', 'As a Data Scientist at ElectrifAi ,  you will be part of a global team of data scientists working on products and solutions for Fortune 500 companies. You will improve upon an... More Details', 'hive  ,  algorithms  ,  data mining  ,  sql  ,  hadoop  ,  big data  ,  python  ,  natural language processing  ,  machine learning')
('Analytics Vidhya', '5 - 8 yrs', 'Data ScientistData Scientist Dollarbird Information Services Pvt ,  Ltd.mysuru INR 5 - 10 LPA Experience : 5 - 15 YRS. Openings: 3Details:DollarBird is looking to add a Data S... More Details', 'ds  ,  big data  ,  python  ,  oracle  ,  mining  ,  dsp  ,  bi  ,  storage  ,  sql  ,  database  ,  hadoop  ,  crm  ,  mobile  ,  machine learning')
('Sentieo', '0 - 3 yrs', 'Sentieo is powering the future of financial and corporate research in a $30B market. Our vision is to create a world where competitive organizations have the insights they nee... More Details', 'algorithms  ,  data mining  ,  database  ,  python  ,  mining  ,  machine learning')
('Beno Staffing', '2 - 5 yrs', 'What do we do at BluePi: BluePi is a born in cloud organization with one of the main focus area being Big Data and Analytics. At BluePi we solve different business problems fo... More Details', 'image processing  ,  algorithms  ,  natural language processing  ,  machine learning  ,  sql  ,  hadoop  ,  big data')
('Analytics Vidhya', '2 - 7 yrs', 'Description If you want to forecast Indias eCommerce demand within 3 PERCENT  margin ,  build consumer models and scores for 50 million online shoppers ,  or decide the locati... More Details', 'algorithms  ,  c    ,  ensemble  ,  ds  ,  security  ,  hadoop  ,  press  ,  big data  ,  mongodb  ,  python  ,  machine learning  ,  nosql  ,  neo4j')
('Analytics Vidhya', '2 - 5 yrs', 'Data ScientistData Scientist A Client of Analytics VidhyaDelhi ,  Gurugram INR 1 - 2 LPA Experience : 2 - 5 YRS. Openings: 1Details:The ideal candidate is adept at using large... More Details', 'hive  ,  algorithms  ,  data mining  ,  sql  ,  pig  ,  d3.js  ,  mongodb  ,  hbase  ,  python  ,  businessobjects  ,  problem solving  ,  machine learning  ,  nosql  ,  artificial neural networks  ,  cassandra')
('Pattem Digital Technologies', '0 - 3 yrs', 'Data Scientist We are searching for a Lead Data Scientist to lead our technical team and help us gain useful insights from heaps of raw data.Your responsibilities as a Data Sc... More Details', 'python  ,  data mining  ,  machine learning  ,  sql  ,  nosql  ,  leadership skills  ,  big data')
('MASTERCARD', '2 - 3 yrs', 'Job TitleData ScientistJob Description Integrated Analytics Team  Data ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform an... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')
('MASTERCARD', '2 - 3 yrs', 'Job TitleData ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform and guide Mastercards Strategy ,  Product Design and Innova... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')
('MASTERCARD', '2 - 3 yrs', 'Job TitleData ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform and guide Mastercards Strategy ,  Product Design and Innova... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')
('MASTERCARD', '0 - 3 yrs', 'Job TitleData ScientistJob Description Integrated Analytics Team  Data ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform an... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')

In [11]:
import sqlalchemy
engine = sqlalchemy.create_engine('mysql://root:apple123@127.0.0.1') # connect to server

engine.execute("USE mydb")

In [12]:
# Insert whole DataFrame into MySQL
df.to_sql('mydata_table', con = engine, if_exists = 'append', chunksize = 1000,index=False)

In [13]:
# Execute query
sql = "SELECT * FROM mydata_table"
mycursor.execute(sql)
# Fetch all the records
result = mycursor.fetchall()
for i in result:
    print(i)

('Analytics Vidhya', '2 - 5 yrs', 'Data ScientistData Scientist RefreshmintGurgaon INR 4 - 9 LPA Experience : 1 - 3 YRS. Openings: 1Details:Do you feel passionately about solving problems through data? Have you... More Details', 'sas  ,  data science  ,  use cases  ,  predictive modeling  ,  data scientist')
('Analytics Vidhya', '3 - 6 yrs', 'This Role Is Best Suited ForPerson with 3  years of experience in data science. The person should have prior experience with practical data science applications and use cases.... More Details', 'sas  ,  data science  ,  use cases  ,  predictive modeling  ,  data scientist')
('Analytics Vidhya', '3 - 5 yrs', 'Use SAP ,  Tableau and Success Factors IT tools to derive insights from dataApply statistical knowledge to develop data modelsBuild Excel workbooks  ( including VBA ) Prepare ... More Details', 'it tools  ,  tableau  ,  java  ,  vba  ,  data scientist  ,  statistical modeling  ,  visual basic')
('Great Learning', '0 - 3 yrs', 'Involve in the residency class room sessions to facilitate lectures and lab sessionsBe the first point contact for participants for academic queries and manage discussion grou... More Details', 'data analysis  ,  program management  ,  dashboards  ,  tableau  ,  use cases  ,  data scientist')
('Analytics Vidhya', '4 - 7 yrs', 'Data Scientist  Delhi NCR  ( 4  years of experience ) Data Scientist  Delhi NCR  ( 4  years of experience )  A Client of Analytics VidhyaGurugram INR 12 - 17 LPA Experience : ... More Details', 'information technology  ,  business process  ,  data science  ,  predictive modeling  ,  data scientist  ,  statistical modeling')
('Analytics Vidhya', '5 - 8 yrs', 'The data scientist is responsible for solving complex big-data problems in the mobile space using data mining ,  machine learning ,  statistical analysis and common sense. The... More Details', 'data mining  ,  mobile  ,  business analysis  ,  sql  ,  predictive modeling  ,  data scientist  ,  text mining  ,  statistical analysis')
('Analytics Vidhya', '3 - 6 yrs', 'The Data Scientist will support our business leads ,  business analysts and data engineers on data ,  analytics and BI initiatives and will ensure the delivery of actionable a... More Details', 'visualization  ,  bi  ,  dashboards  ,  data science  ,  data scientist  ,  statistical modeling  ,  consulting  ,  predictive analytics  ,  tableau')
('Analytics Vidhya', '4 - 7 yrs', 'Data Scientist- Noida  ( 1-3 Years Of Experience ) Data Scientist- Noida  ( 1-3 Years Of Experience )  A Client of Analytics VidhyaNoida INR 4 - 8 LPA Experience : 1 - 3 YRS. ... More Details', 'data mining  ,  linear regression  ,  sql  ,  data science  ,  data scientist  ,  cluster analysis  ,  logistic regression  ,  sas  ,  consulting  ,  predictive analytics  ,  vba')
('Analytics Vidhya', '3 - 10 yrs', 'Requirements: You have expertise in exploratory data analysis and visualisation  ( e.g. with SQL ,  Python / Pandas ,  R ,  or similar ) .You love using data to answer high-le... More Details', 'data analysis  ,  data analytics  ,  sas  ,  data mining  ,  product roadmap  ,  sql  ,  data science  ,  use cases  ,  predictive modeling  ,  data scientist')
('ITFORTE STAFFING SERVICES PRIVATE LTD', '3 - 6 yrs', 'Data Scientist for GurgaonJob ID IT JOBS#258Location: Gurgaon ,  IndiaRequired Skills: Our client is seeking a creative Data Scientist to explore unstructured data from divers... More Details', 'time series analysis  ,  signal processing  ,  data science  ,  data scientist  ,  statistical modeling  ,  text mining  ,  data analysis  ,  statistical analysis')
('axmiyan hr solutions private limited', '3 - 6 yrs', 'Be an Individual Contributor in the Analytics Research and Development team and solve real-world problems using cutting-edge capabilities and emerging technologies. Be a part ... More Details', 'time series analysis  ,  linear regression  ,  data science  ,  data scientist  ,  logistic regression  ,  image processing  ,  advanced analytics  ,  factor analysis')
('Crowe LLP', '0 - 4 yrs', 'About Crowe Data ScienceEverything we do is about making the future of human work more purposeful. We do this by leveraging state-of-the-art machine learning ,  modern archite... More Details', 'docker  ,  git  ,  data structures  ,  python  ,  machine learning')
('Analytics Vidhya', '5 - 8 yrs', 'Data ScientistData Scientist A Client of Analytics VidhyaGurgaon INR 10 - 15 LPA Experience : 2 - 4 YRS. Openings: 3Details:About the companyStarted 5 years ago ,  today it is... More Details', 'algorithms  ,  python  ,  data mining  ,  machine learning  ,  mysql')
('Team Computers Pvt Ltd', '0 - 3 yrs', 'Position description: The purpose of this role is to closely work with business to identify and implement predictive models for healthcare.Primary Responsibilities:Model for r... More Details', 'data visualization  ,   statistical testing  ,   regression  ,   machine learning techniques')
('electrifai', '10 - 13 yrs', 'As a Data Scientist at ElectrifAi ,  you will be part of a global team of data scientists working on products and solutions for Fortune 500 companies. You will improve upon an... More Details', 'hive  ,  algorithms  ,  data mining  ,  sql  ,  hadoop  ,  big data  ,  python  ,  natural language processing  ,  machine learning')
('Analytics Vidhya', '5 - 8 yrs', 'Data ScientistData Scientist Dollarbird Information Services Pvt ,  Ltd.mysuru INR 5 - 10 LPA Experience : 5 - 15 YRS. Openings: 3Details:DollarBird is looking to add a Data S... More Details', 'ds  ,  big data  ,  python  ,  oracle  ,  mining  ,  dsp  ,  bi  ,  storage  ,  sql  ,  database  ,  hadoop  ,  crm  ,  mobile  ,  machine learning')
('Sentieo', '0 - 3 yrs', 'Sentieo is powering the future of financial and corporate research in a $30B market. Our vision is to create a world where competitive organizations have the insights they nee... More Details', 'algorithms  ,  data mining  ,  database  ,  python  ,  mining  ,  machine learning')
('Beno Staffing', '2 - 5 yrs', 'What do we do at BluePi: BluePi is a born in cloud organization with one of the main focus area being Big Data and Analytics. At BluePi we solve different business problems fo... More Details', 'image processing  ,  algorithms  ,  natural language processing  ,  machine learning  ,  sql  ,  hadoop  ,  big data')
('Analytics Vidhya', '2 - 7 yrs', 'Description If you want to forecast Indias eCommerce demand within 3 PERCENT  margin ,  build consumer models and scores for 50 million online shoppers ,  or decide the locati... More Details', 'algorithms  ,  c    ,  ensemble  ,  ds  ,  security  ,  hadoop  ,  press  ,  big data  ,  mongodb  ,  python  ,  machine learning  ,  nosql  ,  neo4j')
('Analytics Vidhya', '2 - 5 yrs', 'Data ScientistData Scientist A Client of Analytics VidhyaDelhi ,  Gurugram INR 1 - 2 LPA Experience : 2 - 5 YRS. Openings: 1Details:The ideal candidate is adept at using large... More Details', 'hive  ,  algorithms  ,  data mining  ,  sql  ,  pig  ,  d3.js  ,  mongodb  ,  hbase  ,  python  ,  businessobjects  ,  problem solving  ,  machine learning  ,  nosql  ,  artificial neural networks  ,  cassandra')
('Pattem Digital Technologies', '0 - 3 yrs', 'Data Scientist We are searching for a Lead Data Scientist to lead our technical team and help us gain useful insights from heaps of raw data.Your responsibilities as a Data Sc... More Details', 'python  ,  data mining  ,  machine learning  ,  sql  ,  nosql  ,  leadership skills  ,  big data')
('MASTERCARD', '2 - 3 yrs', 'Job TitleData ScientistJob Description Integrated Analytics Team  Data ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform an... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')
('MASTERCARD', '2 - 3 yrs', 'Job TitleData ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform and guide Mastercards Strategy ,  Product Design and Innova... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')
('MASTERCARD', '2 - 3 yrs', 'Job TitleData ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform and guide Mastercards Strategy ,  Product Design and Innova... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')
('MASTERCARD', '0 - 3 yrs', 'Job TitleData ScientistJob Description Integrated Analytics Team  Data ScientistOverviewIntegrated Analytics has pioneered a transaction based revenue methodology to inform an... More Details', 'information technology  ,  ssrs  ,  python  ,  data mining  ,  bi  ,  sql coding  ,  hadoop  ,  problem solving  ,  team player')

In [14]:
# Close the connection
if (mydb.is_connected()):
    mycursor.close()
    mydb.close()