In [1]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import time

URL = ("https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&txtKeywords=Data+Analyst&txtLocation=Delhi")
#conducting a request of the stated URL above:
page3 = requests.get(URL)
#specifying a desired format of “page” using the html parser - this allows python to read the various components of the page, rather than treating it as one long string.
soup = BeautifulSoup( page3.text, "html.parser")

In [2]:
jobs=soup.find_all('li',class_='clearfix job-bx wht-shd-bx')

In [3]:
for job in jobs:
    company=[]
    company1= job.find('h3',class_ ='joblist-comp-name')
    company.append(company1.text.strip())

In [4]:
print(company)

['APPLYCUP HIRING SOLUTIONS LLP']

In [5]:
company=[]
for job in jobs:
    company1= job.find('h3',class_ ='joblist-comp-name')
    company.append(company1.text.strip())

In [6]:
print(company)

['Fine Jobs Consultant Pvt. Ltd.', 'Faircent.com', 'Analytics Vidhya', 'Ameriprise India Pvt Ltd', 'Ameriprise India Pvt Ltd', 'Analytics Vidhya', 'Taboola', 'IKON', 'SEVEN CONSULTANCY', 'ANR SOFTWARE PVT LTD', 'SEVEN CONSULTANCY', 'RGF Professional', 'Cognizant Technology Solutions', 'Cognizant Technology Solutions', 'Forstaffing', 'FresherMart', 'Analytics Vidhya', 'Analytics Vidhya', 'Analytics Vidhya', 'Ground Truth', 'HR DEVI AND ASSOCIATES', 'CashKaro', 'DecisionTree Analytics and Services', 'BUSISOL SOURCING INDIA PVT. LTD', 'APPLYCUP HIRING SOLUTIONS LLP']

In [7]:
year_of_experience =[]
for job in jobs:
    years=job.find('ul', class_='top-jd-dtl clearfix')
    for years in jobs:
        year=years.find('li').text.replace('card_travel','')
        
        year_of_experience.append(year.strip())

In [8]:
year_of_experience

['0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '2 - 4 yrs',
 '1 - 3 yrs',
 '1 - 3 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 3 yrs',
 '0 - 1 yrs',
 '0 - 3 yrs',
 '3 - 6 yrs',
 '0 - 3 yrs',
 '0 - 3 yrs',
 '3 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '2 - 5 yrs',
 '3 - 5 yrs',
 '1 - 2 yrs',
 '4 - 7 yrs',
 '4 - 7 yrs',
 '1 - 3 yrs',
 '0 - 3 yrs',
 '2 - 5 yrs']

In [9]:
skills=[]
for job in jobs:
    skills1=job.find('span',class_='srp-skills').text
    skills.append(skills1.strip())

In [10]:
skills

['data analysis  ,  consulting  ,  it consulting  ,  data analyst  ,  infrastructure',
 'data analytics  ,  vba  ,  data analyst  ,  sql',
 'data analysis  ,  predictive analytics  ,  spss  ,  data analyst  ,  sql  ,  factor analysis',
 'business requirements  ,  advanced analytics  ,  sas  ,  business analysis  ,  data analyst  ,  tableau  ,  written communication  ,  predictive modeling',
 'business requirements  ,  advanced analytics  ,  sas  ,  business analysis  ,  data analyst  ,  tableau  ,  written communication  ,  predictive modeling  ,  sql programming',
 'data analytics  ,  sas  ,  spss  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  statistical modeling  ,  data visualization',
 'data analytics  ,  data analysis  ,  bi  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  crm',
 'bi  ,  sql  ,  requirement gathering  ,  database  ,  advanced excel  ,  data visualization  ,  data analysis  ,  data analyst  ,  alteryx  ,  tableau',
 'data analytics  ,  big data analytics  ,  data mining  ,  data reports  ,  data analyst  ,  database  ,  data science  ,  data scientist  ,  analyst',
 'data analytics  ,  information management  ,  sas  ,  spss  ,  data analyst  ,  sql  ,  data science  ,  written communication',
 'data analytics  ,  big data analytics  ,  data mining  ,  consulting  ,  data reports  ,  data analyst  ,  database  ,  data science  ,  data scientist  ,  analyst',
 'dashboards  ,  sql  ,  database  ,  data visualization  ,  tableau  ,  vba  ,  written communication  ,  analyst',
 'reports  ,  mentor  ,  customer interaction  ,  coding  ,  database  ,  security  ,  procedures  ,  c',
 'reports  ,  mentor  ,  customer interaction  ,  coding  ,  database  ,  security  ,  procedures  ,  c',
 'mdx  ,  ssas  ,  olap  ,  sql',
 'sql queries  ,   vb  ,   Excel Macros  ,   VB',
 'bi  ,  business intelligence  ,  sql  ,  qlikview',
 'python  ,  sql  ,  messaging  ,  infrastructure',
 'python  ,  problem solving  ,  reporting tools',
 'python  ,  mobile  ,  sql  ,  database  ,  written communication  ,  infrastructure  ,  linux',
 'data mining  ,  sql  ,  sql developer  ,  python  ,  business objects',
 'data analysis  ,  data analytics  ,  bi  ,  dashboards  ,  sql  ,  tableau  ,  advanced excel',
 'data mining  ,  sql  ,  postgresql  ,  mysql  ,  product delivery  ,  written communication',
 'reports  ,  charts  ,  data mining  ,  formulas  ,  reporting services  ,  relational database  ,  sql server',
 'ssas  ,  business intelligence  ,  business intelligence tools  ,  ssis  ,  data integration']

In [11]:
description=[]
for job in jobs:
    des=job.find('ul',class_='list-job-dtl clearfix')
    des1=des.li.text.replace('Job Description:','')
    
    
    description.append(des1.strip())

In [12]:
description

['Job DescriptionVARITE is looking for a qualified Data Analyst for one of its clients located in Noida  ( Sec 144 )  . If you are interested in this opportunity ,  kindly respo... More Details',
 'Job Responsibilities:Candidate must have the following basic requirements:Minimum Experience - 3 Yrs.industry - FintechTechnicals - SQL ,  Python ,  VBA ,  XLSShould be based ... More Details',
 'Job Description and Responsibilities:- Work with Product teams to identify opportunities for product enhancement based on data driven insights.- Collaborate with sales and mar... More Details',
 'We are looking for a driven individual with analytical mindset who is ready for an immersive ,  real-world experience. You should be a motivated team player who can maintain e... More Details',
 'Job DescriptionWe are looking for a driven individual with analytical mindset who is ready for an immersive ,  real-world experience. You should be a motivated team player who... More Details',
 'Data Analyst- Gurugram  ( 2  Years Of Experience ) Data Analyst- Gurugram  ( 2  Years Of Experience )  A Client of Analytics Vidhyamultiple INR 5 - 9 LPA Experience : 2 YRS. O... More Details',
 'Responsibilities:Create ,  support and maintain reports and dashboards ,  as well as find creative solutions for a variety of challenges ,  while facing our growing data requi... More Details',
 'zRoles and ResponsibilitiesKEY TASKSRequirement gathering and evaluation of clients business situations in order to implement appropriate analytic solutions.Data management an... More Details',
 'JOB DETAILS1.Importing / Collecting ,  cleaning ,  converting and analyzing the data for the purpose of find insights and making conclusions.2.Presenting data in graphs ,  cha... More Details',
 'Data AnalystExperience: 0 to 1 YearsEligibility  &  Job Description Eligibility: Bachelor degree in Mathematics ,  Computer Science ,  Information Management or StatisticsAny ... More Details',
 '1.Importing / Collecting ,  cleaning ,  converting and analyzing the data for the purpose of find insights and making conclusions.2.Presenting data in graphs ,  charts ,  tabl... More Details',
 'Job Description Key Responsibilities Collate ,  compile ,  mine and present a broad range of data for internal purposes ,  primarily focussed on investment management process ... More Details',
 'Team Lead - CDM / PVQualification:Graduate / Post Graduate /  Doctorate degree in life sciences / Pharmacy / Medical sciences / Registered Nurse Responsibility:Business /  Cus... More Details',
 'Team Lead - CDM / PVQualification:Graduate / Post Graduate /  Doctorate degree in life sciences / Pharmacy / Medical sciences / Registered Nurse Responsibility:Business /  Cus... More Details',
 'ideally with relevant experience 3-5 yrs.must have strong experience working on MS SSAS /  OLAP  /  Cube technologies  (  DAX ,  MDX ) .must have created  &  maintained cubes ... More Details',
 'Candidate should have worked for at least 2 years work experience Should have worked with a team of at least 20 people Should be VERY GOOD with the use of Excel ,  Excel Macro... More Details',
 'Data AnalystData Analyst ConfidentialDelhi NCR ,  Mumbai ,  Bengaluru ,  Hyderabad ,  Pune INR 4 - 5 LPA Experience : 2 - 5 YRS. Openings: 10Details:Person with 2  years of ex... More Details',
 'This role is on our Analytics team. This team partners with Product  &  Editorial to produce world-class analysis and provide recommendations that improve our products and inc... More Details',
 'Data Analyst- Delhi / NCR / Gurugram-  ( 3-5 Years Of Experience ) Data Analyst- Delhi / NCR / Gurugram-  ( 3-5 Years Of Experience )  A Client of Analytics VidhyaDelhi ,  Gur... More Details',
 'We believe that innovative technology starts with the best talent and were recently ranked of Ad Ages 2021 Best Places to Work. Learn more about the perks of joining our team ... More Details',
 'Responsibilities:Interpret data ,  analyze results using statistical techniques and provide ongoing reports.develop and implement data collection systems and other strategies ... More Details',
 "With CashKaro's recent $10mn Series B fundraise ,  we are looking to grow 10x. This can be a great career move to accelerate your own growth.Roles and responsibilities of this... More Details",
 'Position Summary:DecisionTree is looking for a Data Analyst to manage services delivery and analytics product delivery. You should have a proven track record in delivering ana... More Details',
 'Job description : We are looking for an experienced Data Analyst ,  who possesses most or all of the following qualities: - Self-starter ,  able to work on his own with little... More Details',
 'Qualification : Any Graduate Experience : 2 - 3 YearsSkills : Data Analyst ,  Data Driven service ,  Complex Behavioral Analysis ,  Statistical Models ,  Development of Data ,... More Details']

In [13]:
link=[]
for job in jobs:
    link1=job.header.h2.a['href']
    link.append(link1)

In [14]:
link

['https://www.timesjobs.com/job-detail/data-analyst-fine-jobs-consultant-pvt-ltd-noida-greater-noida-0-to-3-yrs-jobid-HDm__SLASH__gOLtzw5zpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-faircent-com-gurgaon-3-to-6-yrs-jobid-wYIhqM3JMvhzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-gurgaon-2-to-4-yrs-jobid-xQXq8fgvS01zpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-ameriprise-india-pvt-ltd-gurgaon-1-to-3-yrs-jobid-l__PLUS__91C3P7xMBzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-ameriprise-india-pvt-ltd-noida-greater-noida-1-to-3-yrs-jobid-V45sc2cj1HpzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-gurgaon-2-to-5-yrs-jobid-veGhsAe2FU9zpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-taboola-delhi-2-to-5-yrs-jobid-iEaTQ4EjtmRzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-ikon-hyderabad-secunderabad-gurgaon-chennai-pune-bengaluru-bangalore-3-to-5-yrs-jobid-M0ScInEm3whzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-seven-consultancy-delhi-delhi-ncr-1-to-3-yrs-jobid-0yMgXFm__SLASH__q5NzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-anr-software-pvt-ltd-noida-greater-noida-0-to-1-yrs-jobid-wiKqbbFOouJzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-seven-consultancy-delhi-delhi-ncr-0-to-3-yrs-jobid-t09G0NcoWEVzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-rgf-professional-gurgaon-3-to-6-yrs-jobid-SvVvrqj__PLUS__bz9zpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-cognizant-technology-solutions-gurgaon-0-to-3-yrs-jobid-thbbdK3IcnhzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-cognizant-technology-solutions-gurgaon-0-to-3-yrs-jobid-JF__SLASH__wetvYxDNzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-forstaffing-noida-greater-noida-3-to-5-yrs-jobid-cf8qHnDv__PLUS__EdzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-freshermart-gurgaon-2-to-5-yrs-jobid-Qth1ctxnQ0ZzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-hyderabad-secunderabad-mumbai-delhi-delhi-ncr-pune-2-to-5-yrs-jobid-Bw7ZrxrSg__PLUS__1zpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-noida-greater-noida-2-to-5-yrs-jobid-AMMaWFH6RutzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-delhi-delhi-ncr-3-to-5-yrs-jobid-Icxd2xsqxtRzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-ground-truth-gurgaon-1-to-2-yrs-jobid-j1kEE4TAUalzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-hr-devi-and-associates-gurgaon-4-to-7-yrs-jobid-Y1VT0WCc7phzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-cashkaro-gurgaon-4-to-7-yrs-jobid-__PLUS__7SYvEx9Pq5zpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-decisiontree-analytics-and-services-gurgaon-1-to-3-yrs-jobid-yiarx__PLUS__Iid0hzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-busisol-sourcing-india-pvt-ltd-delhi-0-to-3-yrs-jobid-8prYmLkFDLdzpSvf__PLUS__uAgZw==&source=srp',
 'https://www.timesjobs.com/job-detail/data-analyst-applycup-hiring-solutions-llp-delhi-delhi-ncr-2-to-5-yrs-jobid-7gGd1uc6su5zpSvf__PLUS__uAgZw==&source=srp']

In [15]:
published_date=[]
for job in jobs:
    published_date1=job.find('span',class_='sim-posted').text
    published_date.append(published_date1.strip())

In [16]:
published_date

['Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted 2 days ago',
 'Posted 5 days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted 4 days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted 5 days ago',
 'Posted 2 days ago',
 'Posted 3 days ago',
 'Posted 4 days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago',
 'Posted few days ago']

In [17]:
data_tuples = list(zip(company,year_of_experience,description,skills,link))

In [18]:
data_tuples

[('Fine Jobs Consultant Pvt. Ltd.',
  '0 - 3 yrs',
  'Job DescriptionVARITE is looking for a qualified Data Analyst for one of its clients located in Noida  ( Sec 144 )  . If you are interested in this opportunity ,  kindly respo... More Details',
  'data analysis  ,  consulting  ,  it consulting  ,  data analyst  ,  infrastructure',
  'https://www.timesjobs.com/job-detail/data-analyst-fine-jobs-consultant-pvt-ltd-noida-greater-noida-0-to-3-yrs-jobid-HDm__SLASH__gOLtzw5zpSvf__PLUS__uAgZw==&source=srp'),
 ('Faircent.com',
  '3 - 6 yrs',
  'Job Responsibilities:Candidate must have the following basic requirements:Minimum Experience - 3 Yrs.industry - FintechTechnicals - SQL ,  Python ,  VBA ,  XLSShould be based ... More Details',
  'data analytics  ,  vba  ,  data analyst  ,  sql',
  'https://www.timesjobs.com/job-detail/data-analyst-faircent-com-gurgaon-3-to-6-yrs-jobid-wYIhqM3JMvhzpSvf__PLUS__uAgZw==&source=srp'),
 ('Analytics Vidhya',
  '2 - 4 yrs',
  'Job Description and Responsibilities:- Work with Product teams to identify opportunities for product enhancement based on data driven insights.- Collaborate with sales and mar... More Details',
  'data analysis  ,  predictive analytics  ,  spss  ,  data analyst  ,  sql  ,  factor analysis',
  'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-gurgaon-2-to-4-yrs-jobid-xQXq8fgvS01zpSvf__PLUS__uAgZw==&source=srp'),
 ('Ameriprise India Pvt Ltd',
  '1 - 3 yrs',
  'We are looking for a driven individual with analytical mindset who is ready for an immersive ,  real-world experience. You should be a motivated team player who can maintain e... More Details',
  'business requirements  ,  advanced analytics  ,  sas  ,  business analysis  ,  data analyst  ,  tableau  ,  written communication  ,  predictive modeling',
  'https://www.timesjobs.com/job-detail/data-analyst-ameriprise-india-pvt-ltd-gurgaon-1-to-3-yrs-jobid-l__PLUS__91C3P7xMBzpSvf__PLUS__uAgZw==&source=srp'),
 ('Ameriprise India Pvt Ltd',
  '1 - 3 yrs',
  'Job DescriptionWe are looking for a driven individual with analytical mindset who is ready for an immersive ,  real-world experience. You should be a motivated team player who... More Details',
  'business requirements  ,  advanced analytics  ,  sas  ,  business analysis  ,  data analyst  ,  tableau  ,  written communication  ,  predictive modeling  ,  sql programming',
  'https://www.timesjobs.com/job-detail/data-analyst-ameriprise-india-pvt-ltd-noida-greater-noida-1-to-3-yrs-jobid-V45sc2cj1HpzpSvf__PLUS__uAgZw==&source=srp'),
 ('Analytics Vidhya',
  '2 - 5 yrs',
  'Data Analyst- Gurugram  ( 2  Years Of Experience ) Data Analyst- Gurugram  ( 2  Years Of Experience )  A Client of Analytics Vidhyamultiple INR 5 - 9 LPA Experience : 2 YRS. O... More Details',
  'data analytics  ,  sas  ,  spss  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  statistical modeling  ,  data visualization',
  'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-gurgaon-2-to-5-yrs-jobid-veGhsAe2FU9zpSvf__PLUS__uAgZw==&source=srp'),
 ('Taboola',
  '2 - 5 yrs',
  'Responsibilities:Create ,  support and maintain reports and dashboards ,  as well as find creative solutions for a variety of challenges ,  while facing our growing data requi... More Details',
  'data analytics  ,  data analysis  ,  bi  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  crm',
  'https://www.timesjobs.com/job-detail/data-analyst-taboola-delhi-2-to-5-yrs-jobid-iEaTQ4EjtmRzpSvf__PLUS__uAgZw==&source=srp'),
 ('IKON',
  '3 - 5 yrs',
  'zRoles and ResponsibilitiesKEY TASKSRequirement gathering and evaluation of clients business situations in order to implement appropriate analytic solutions.Data management an... More Details',
  'bi  ,  sql  ,  requirement gathering  ,  database  ,  advanced excel  ,  data visualization  ,  data analysis  ,  data analyst  ,  alteryx  ,  tableau',
  'https://www.timesjobs.com/job-detail/data-analyst-ikon-hyderabad-secunderabad-gurgaon-chennai-pune-bengaluru-bangalore-3-to-5-yrs-jobid-M0ScInEm3whzpSvf__PLUS__uAgZw==&source=srp'),
 ('SEVEN CONSULTANCY',
  '1 - 3 yrs',
  'JOB DETAILS1.Importing / Collecting ,  cleaning ,  converting and analyzing the data for the purpose of find insights and making conclusions.2.Presenting data in graphs ,  cha... More Details',
  'data analytics  ,  big data analytics  ,  data mining  ,  data reports  ,  data analyst  ,  database  ,  data science  ,  data scientist  ,  analyst',
  'https://www.timesjobs.com/job-detail/data-analyst-seven-consultancy-delhi-delhi-ncr-1-to-3-yrs-jobid-0yMgXFm__SLASH__q5NzpSvf__PLUS__uAgZw==&source=srp'),
 ('ANR SOFTWARE PVT LTD',
  '0 - 1 yrs',
  'Data AnalystExperience: 0 to 1 YearsEligibility  &  Job Description Eligibility: Bachelor degree in Mathematics ,  Computer Science ,  Information Management or StatisticsAny ... More Details',
  'data analytics  ,  information management  ,  sas  ,  spss  ,  data analyst  ,  sql  ,  data science  ,  written communication',
  'https://www.timesjobs.com/job-detail/data-analyst-anr-software-pvt-ltd-noida-greater-noida-0-to-1-yrs-jobid-wiKqbbFOouJzpSvf__PLUS__uAgZw==&source=srp'),
 ('SEVEN CONSULTANCY',
  '0 - 3 yrs',
  '1.Importing / Collecting ,  cleaning ,  converting and analyzing the data for the purpose of find insights and making conclusions.2.Presenting data in graphs ,  charts ,  tabl... More Details',
  'data analytics  ,  big data analytics  ,  data mining  ,  consulting  ,  data reports  ,  data analyst  ,  database  ,  data science  ,  data scientist  ,  analyst',
  'https://www.timesjobs.com/job-detail/data-analyst-seven-consultancy-delhi-delhi-ncr-0-to-3-yrs-jobid-t09G0NcoWEVzpSvf__PLUS__uAgZw==&source=srp'),
 ('RGF Professional',
  '3 - 6 yrs',
  'Job Description Key Responsibilities Collate ,  compile ,  mine and present a broad range of data for internal purposes ,  primarily focussed on investment management process ... More Details',
  'dashboards  ,  sql  ,  database  ,  data visualization  ,  tableau  ,  vba  ,  written communication  ,  analyst',
  'https://www.timesjobs.com/job-detail/data-analyst-rgf-professional-gurgaon-3-to-6-yrs-jobid-SvVvrqj__PLUS__bz9zpSvf__PLUS__uAgZw==&source=srp'),
 ('Cognizant Technology Solutions',
  '0 - 3 yrs',
  'Team Lead - CDM / PVQualification:Graduate / Post Graduate /  Doctorate degree in life sciences / Pharmacy / Medical sciences / Registered Nurse Responsibility:Business /  Cus... More Details',
  'reports  ,  mentor  ,  customer interaction  ,  coding  ,  database  ,  security  ,  procedures  ,  c',
  'https://www.timesjobs.com/job-detail/data-analyst-cognizant-technology-solutions-gurgaon-0-to-3-yrs-jobid-thbbdK3IcnhzpSvf__PLUS__uAgZw==&source=srp'),
 ('Cognizant Technology Solutions',
  '0 - 3 yrs',
  'Team Lead - CDM / PVQualification:Graduate / Post Graduate /  Doctorate degree in life sciences / Pharmacy / Medical sciences / Registered Nurse Responsibility:Business /  Cus... More Details',
  'reports  ,  mentor  ,  customer interaction  ,  coding  ,  database  ,  security  ,  procedures  ,  c',
  'https://www.timesjobs.com/job-detail/data-analyst-cognizant-technology-solutions-gurgaon-0-to-3-yrs-jobid-JF__SLASH__wetvYxDNzpSvf__PLUS__uAgZw==&source=srp'),
 ('Forstaffing',
  '3 - 5 yrs',
  'ideally with relevant experience 3-5 yrs.must have strong experience working on MS SSAS /  OLAP  /  Cube technologies  (  DAX ,  MDX ) .must have created  &  maintained cubes ... More Details',
  'mdx  ,  ssas  ,  olap  ,  sql',
  'https://www.timesjobs.com/job-detail/data-analyst-forstaffing-noida-greater-noida-3-to-5-yrs-jobid-cf8qHnDv__PLUS__EdzpSvf__PLUS__uAgZw==&source=srp'),
 ('FresherMart',
  '2 - 5 yrs',
  'Candidate should have worked for at least 2 years work experience Should have worked with a team of at least 20 people Should be VERY GOOD with the use of Excel ,  Excel Macro... More Details',
  'sql queries  ,   vb  ,   Excel Macros  ,   VB',
  'https://www.timesjobs.com/job-detail/data-analyst-freshermart-gurgaon-2-to-5-yrs-jobid-Qth1ctxnQ0ZzpSvf__PLUS__uAgZw==&source=srp'),
 ('Analytics Vidhya',
  '2 - 5 yrs',
  'Data AnalystData Analyst ConfidentialDelhi NCR ,  Mumbai ,  Bengaluru ,  Hyderabad ,  Pune INR 4 - 5 LPA Experience : 2 - 5 YRS. Openings: 10Details:Person with 2  years of ex... More Details',
  'bi  ,  business intelligence  ,  sql  ,  qlikview',
  'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-hyderabad-secunderabad-mumbai-delhi-delhi-ncr-pune-2-to-5-yrs-jobid-Bw7ZrxrSg__PLUS__1zpSvf__PLUS__uAgZw==&source=srp'),
 ('Analytics Vidhya',
  '2 - 5 yrs',
  'This role is on our Analytics team. This team partners with Product  &  Editorial to produce world-class analysis and provide recommendations that improve our products and inc... More Details',
  'python  ,  sql  ,  messaging  ,  infrastructure',
  'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-noida-greater-noida-2-to-5-yrs-jobid-AMMaWFH6RutzpSvf__PLUS__uAgZw==&source=srp'),
 ('Analytics Vidhya',
  '3 - 5 yrs',
  'Data Analyst- Delhi / NCR / Gurugram-  ( 3-5 Years Of Experience ) Data Analyst- Delhi / NCR / Gurugram-  ( 3-5 Years Of Experience )  A Client of Analytics VidhyaDelhi ,  Gur... More Details',
  'python  ,  problem solving  ,  reporting tools',
  'https://www.timesjobs.com/job-detail/data-analyst-analytics-vidhya-delhi-delhi-ncr-3-to-5-yrs-jobid-Icxd2xsqxtRzpSvf__PLUS__uAgZw==&source=srp'),
 ('Ground Truth',
  '1 - 2 yrs',
  'We believe that innovative technology starts with the best talent and were recently ranked of Ad Ages 2021 Best Places to Work. Learn more about the perks of joining our team ... More Details',
  'python  ,  mobile  ,  sql  ,  database  ,  written communication  ,  infrastructure  ,  linux',
  'https://www.timesjobs.com/job-detail/data-analyst-ground-truth-gurgaon-1-to-2-yrs-jobid-j1kEE4TAUalzpSvf__PLUS__uAgZw==&source=srp'),
 ('HR DEVI AND ASSOCIATES',
  '4 - 7 yrs',
  'Responsibilities:Interpret data ,  analyze results using statistical techniques and provide ongoing reports.develop and implement data collection systems and other strategies ... More Details',
  'data mining  ,  sql  ,  sql developer  ,  python  ,  business objects',
  'https://www.timesjobs.com/job-detail/data-analyst-hr-devi-and-associates-gurgaon-4-to-7-yrs-jobid-Y1VT0WCc7phzpSvf__PLUS__uAgZw==&source=srp'),
 ('CashKaro',
  '4 - 7 yrs',
  "With CashKaro's recent $10mn Series B fundraise ,  we are looking to grow 10x. This can be a great career move to accelerate your own growth.Roles and responsibilities of this... More Details",
  'data analysis  ,  data analytics  ,  bi  ,  dashboards  ,  sql  ,  tableau  ,  advanced excel',
  'https://www.timesjobs.com/job-detail/data-analyst-cashkaro-gurgaon-4-to-7-yrs-jobid-__PLUS__7SYvEx9Pq5zpSvf__PLUS__uAgZw==&source=srp'),
 ('DecisionTree Analytics and Services',
  '1 - 3 yrs',
  'Position Summary:DecisionTree is looking for a Data Analyst to manage services delivery and analytics product delivery. You should have a proven track record in delivering ana... More Details',
  'data mining  ,  sql  ,  postgresql  ,  mysql  ,  product delivery  ,  written communication',
  'https://www.timesjobs.com/job-detail/data-analyst-decisiontree-analytics-and-services-gurgaon-1-to-3-yrs-jobid-yiarx__PLUS__Iid0hzpSvf__PLUS__uAgZw==&source=srp'),
 ('BUSISOL SOURCING INDIA PVT. LTD',
  '0 - 3 yrs',
  'Job description : We are looking for an experienced Data Analyst ,  who possesses most or all of the following qualities: - Self-starter ,  able to work on his own with little... More Details',
  'reports  ,  charts  ,  data mining  ,  formulas  ,  reporting services  ,  relational database  ,  sql server',
  'https://www.timesjobs.com/job-detail/data-analyst-busisol-sourcing-india-pvt-ltd-delhi-0-to-3-yrs-jobid-8prYmLkFDLdzpSvf__PLUS__uAgZw==&source=srp'),
 ('APPLYCUP HIRING SOLUTIONS LLP',
  '2 - 5 yrs',
  'Qualification : Any Graduate Experience : 2 - 3 YearsSkills : Data Analyst ,  Data Driven service ,  Complex Behavioral Analysis ,  Statistical Models ,  Development of Data ,... More Details',
  'ssas  ,  business intelligence  ,  business intelligence tools  ,  ssis  ,  data integration',
  'https://www.timesjobs.com/job-detail/data-analyst-applycup-hiring-solutions-llp-delhi-delhi-ncr-2-to-5-yrs-jobid-7gGd1uc6su5zpSvf__PLUS__uAgZw==&source=srp')]

In [19]:
 df=pd.DataFrame(data_tuples, columns=['company','year_of_experience','description','skills','link'])

In [20]:
df.to_csv(r'data_analyst.csv')

In [21]:
df

,company,year_of_experience,description,skills,link
0,Fine Jobs Consultant Pvt. Ltd.,0 - 3 yrs,Job DescriptionVARITE is looking for a qualifi...,"data analysis , consulting , it consulting...",https://www.timesjobs.com/job-detail/data-anal...
1,Faircent.com,3 - 6 yrs,Job Responsibilities:Candidate must have the f...,"data analytics , vba , data analyst , sql",https://www.timesjobs.com/job-detail/data-anal...
2,Analytics Vidhya,2 - 4 yrs,Job Description and Responsibilities:- Work wi...,"data analysis , predictive analytics , sps...",https://www.timesjobs.com/job-detail/data-anal...
3,Ameriprise India Pvt Ltd,1 - 3 yrs,We are looking for a driven individual with an...,"business requirements , advanced analytics ...",https://www.timesjobs.com/job-detail/data-anal...
4,Ameriprise India Pvt Ltd,1 - 3 yrs,Job DescriptionWe are looking for a driven ind...,"business requirements , advanced analytics ...",https://www.timesjobs.com/job-detail/data-anal...
5,Analytics Vidhya,2 - 5 yrs,Data Analyst- Gurugram ( 2 Years Of Experien...,"data analytics , sas , spss , dashboards...",https://www.timesjobs.com/job-detail/data-anal...
6,Taboola,2 - 5 yrs,"Responsibilities:Create , support and maintai...","data analytics , data analysis , bi , da...",https://www.timesjobs.com/job-detail/data-anal...
7,IKON,3 - 5 yrs,zRoles and ResponsibilitiesKEY TASKSRequiremen...,"bi , sql , requirement gathering , datab...",https://www.timesjobs.com/job-detail/data-anal...
8,SEVEN CONSULTANCY,1 - 3 yrs,"JOB DETAILS1.Importing / Collecting , cleanin...","data analytics , big data analytics , data...",https://www.timesjobs.com/job-detail/data-anal...
9,ANR SOFTWARE PVT LTD,0 - 1 yrs,Data AnalystExperience: 0 to 1 YearsEligibilit...,"data analytics , information management , ...",https://www.timesjobs.com/job-detail/data-anal...
10,SEVEN CONSULTANCY,0 - 3 yrs,"1.Importing / Collecting , cleaning , conver...","data analytics , big data analytics , data...",https://www.timesjobs.com/job-detail/data-anal...
11,RGF Professional,3 - 6 yrs,"Job Description Key Responsibilities Collate ,...","dashboards , sql , database , data visua...",https://www.timesjobs.com/job-detail/data-anal...
12,Cognizant Technology Solutions,0 - 3 yrs,Team Lead - CDM / PVQualification:Graduate / P...,"reports , mentor , customer interaction ,...",https://www.timesjobs.com/job-detail/data-anal...
13,Cognizant Technology Solutions,0 - 3 yrs,Team Lead - CDM / PVQualification:Graduate / P...,"reports , mentor , customer interaction ,...",https://www.timesjobs.com/job-detail/data-anal...
14,Forstaffing,3 - 5 yrs,ideally with relevant experience 3-5 yrs.must ...,"mdx , ssas , olap , sql",https://www.timesjobs.com/job-detail/data-anal...
15,FresherMart,2 - 5 yrs,Candidate should have worked for at least 2 ye...,"sql queries , vb , Excel Macros , VB",https://www.timesjobs.com/job-detail/data-anal...
16,Analytics Vidhya,2 - 5 yrs,Data AnalystData Analyst ConfidentialDelhi NCR...,"bi , business intelligence , sql , qlikview",https://www.timesjobs.com/job-detail/data-anal...
17,Analytics Vidhya,2 - 5 yrs,This role is on our Analytics team. This team ...,"python , sql , messaging , infrastructure",https://www.timesjobs.com/job-detail/data-anal...
18,Analytics Vidhya,3 - 5 yrs,Data Analyst- Delhi / NCR / Gurugram- ( 3-5 Y...,"python , problem solving , reporting tools",https://www.timesjobs.com/job-detail/data-anal...
19,Ground Truth,1 - 2 yrs,We believe that innovative technology starts w...,"python , mobile , sql , database , wri...",https://www.timesjobs.com/job-detail/data-anal...
20,HR DEVI AND ASSOCIATES,4 - 7 yrs,"Responsibilities:Interpret data , analyze res...","data mining , sql , sql developer , pyth...",https://www.timesjobs.com/job-detail/data-anal...
21,CashKaro,4 - 7 yrs,With CashKaro's recent $10mn Series B fundrais...,"data analysis , data analytics , bi , da...",https://www.timesjobs.com/job-detail/data-anal...
22,DecisionTree Analytics and Services,1 - 3 yrs,Position Summary:DecisionTree is looking for a...,"data mining , sql , postgresql , mysql ...",https://www.timesjobs.com/job-detail/data-anal...
23,BUSISOL SOURCING INDIA PVT. LTD,0 - 3 yrs,Job description : We are looking for an experi...,"reports , charts , data mining , formula...",https://www.timesjobs.com/job-detail/data-anal...
24,APPLYCUP HIRING SOLUTIONS LLP,2 - 5 yrs,Qualification : Any Graduate Experience : 2 - ...,"ssas , business intelligence , business in...",https://www.timesjobs.com/job-detail/data-anal...